image:
  - Visual Studio 2017
  - Visual Studio 2015

platform:
  - x64

build_script:
  - gradlew.bat assemble --info

test_script:
  - gradlew.bat check --info

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
    # https://www.appveyor.com/docs/windows-images-software/
  - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.7.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files\Java\jdk9
  - JAVA_HOME: C:\Program Files\Java\jdk10

matrix:
  fast_finish: false

build: off
