/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.*;

public class LibraryTest {
    // @Test public void testSomeLibraryMethod() {
    //     Library classUnderTest = new Library();
    //     assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    // }

    @Test public void testNormalDistribution() {
        // create random object
        Random ran = new Random(42);

        assertEquals(8.28381063094611,
                     ran.nextGaussian()*2 + 6,1e-7);

        assertEquals(7.83881589796557,
                     ran.nextGaussian()*2 + 6,1e-7);

        assertEquals(4.100266726218209,
                     ran.nextGaussian()*2 + 6,1e-7);

        assertEquals(3.7860194272013246,
                     ran.nextGaussian()*2 + 6,1e-7);

        assertEquals(6.561955276145559,
                     ran.nextGaussian()*2 + 6,1e-7);
        
    }
}
